### PR TITLE
ODSC-35441: simple random selection for multi-GPU MD

### PR DESCRIPTION
**Pull request by ahosler**

### CODE REVIEW

**Comment by ahosler** [comment]
image
Here's a screenshot of the new whl working on a GPU instance, being verified on the GPU, and then being deployed to a CPU instance.

**Comment by ahosler** [comment]
image
Here's a screenshot of the new whl working on a GPU instance, being verified on the GPU, and then being deployed to a CPU instance.

**Comment by ahosler** [comment]
image

Here's a screenshot of the new whl working on a GPU instance, being verified on the GPU, and then being deployed to a CPU instance.

**Comment by ahosler** [comment]
image
Proof of GPU being recognized when running verify

**Review by mayoor — APPROVED** [review]

**Pull request merged**
